"use client";
import { useState } from "react";
import { ArrowUpRight, Crosshair, Network, ShieldCheck } from "lucide-react";
const stages = [
  { title: "种子识别", icon: Crosshair, description: "从研究问题出发，在本地证据池内识别种子靶点。", label: "SEED IDENTIFICATION", value: "研究问题驱动" },
  { title: "网络扩展", icon: Network, description: "沿功能关联网络传播，拓展与种子相关的候选。", label: "NETWORK PROPAGATION", value: "个性化 PageRank" },
  { title: "证据核查", icon: ShieldCheck, description: "核查证据归属，区分证据支持与网络关联。", label: "EVIDENCE VALIDATION", value: "引用归属可核查" },
];
const points = [[270,205],[163,123],[372,112],[411,245],[297,331],[130,282],[68,170],[258,62],[468,153],[454,343],[153,377],[65,342],[360,406],[503,269],[93,70],[337,25],[516,81],[219,420]];
const edges = [[0,1],[0,2],[0,3],[0,4],[0,5],[1,6],[1,7],[1,14],[2,7],[2,8],[2,15],[3,8],[3,9],[3,13],[4,5],[4,9],[4,10],[4,12],[5,6],[5,10],[5,11],[6,14],[7,15],[8,16],[8,13],[9,12],[10,11],[10,17],[12,17],[13,16],[1,5],[2,3]];
export default function DiscoveryPreview() {
  const [stage,setStage] = useState(1);
  return <div className="discovery-preview"><div className="preview-top"><span><span className="preview-status" /> EXPLORATION ENGINE</span><span>流程示意 / 非分析结果</span></div><div className="preview-canvas"><div className="preview-coordinate">FUNCTIONAL ASSOCIATION<br />HUMAN PROTEIN NETWORK</div><svg viewBox="0 0 560 450" role="img" aria-label="种子靶点向周边候选传播的功能关联网络示意图"><defs><radialGradient id="network-halo"><stop stopColor="#20cdb4" stopOpacity=".15" /><stop offset="1" stopColor="#20cdb4" stopOpacity="0" /></radialGradient></defs><circle cx="270" cy="215" r="225" fill="url(#network-halo)" /><g className="network-orbits"><circle cx="270" cy="215" r="95" /><circle cx="270" cy="215" r="173" /><circle cx="270" cy="215" r="222" /></g><g>{edges.map(([a,b],i)=><line key={i} x1={points[a][0]} y1={points[a][1]} x2={points[b][0]} y2={points[b][1]} className={a===0?"network-link strong":"network-link"} opacity={stage===0&&a!==0?.18:1} />)}</g>{points.map(([x,y],i)=><g key={i} opacity={stage===0&&i>5?.25:1}><circle cx={x} cy={y} r={i===0?34:i<6?18:9} className={i===0?"preview-seed":i<6?"preview-candidate":"preview-neighbor"}/><circle cx={x} cy={y} r={i===0?8:3} fill={stage===2&&i<6?"#a4e3ff":"#53e1c3"}/>{i===0&&<circle cx={x} cy={y} r="45" className="seed-ring"/>}{i<6&&<text x={x} y={y+(i===0?60:34)} textAnchor="middle">{i===0?"SEED TARGET":`CANDIDATE 0${i}`}</text>}</g>)}</svg><div className="network-callout"><ShieldCheck size={16}/><span>让关联可见<b>让依据可查</b></span><ArrowUpRight size={15}/></div><div className="preview-legend"><span><i/>种子靶点</span><span><i/>扩展候选</span><small>关联连线 ≠ 因果关系</small></div></div><div className="preview-tabs" role="tablist" aria-label="探索优选流程">{stages.map(({title,icon:Icon},i)=><button key={title} type="button" role="tab" id={`stage-${i}`} aria-selected={stage===i} aria-controls="stage-description" tabIndex={stage===i?0:-1} onClick={()=>setStage(i)} onKeyDown={e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const next=(i+(e.key==='ArrowRight'?1:2))%3;setStage(next);document.getElementById(`stage-${next}`)?.focus();}}}><Icon size={15}/><span>{title}</span></button>)}</div><div className="preview-description" id="stage-description" role="tabpanel" aria-labelledby={`stage-${stage}`}><div><small>{stages[stage].label}</small><b>{stages[stage].value}</b></div><p>{stages[stage].description}</p></div></div>;
}
